Repository yong-yong-lee/logistics-delivery, pull requests merged in 2024-09, with the labels that each got.

#7 feat(#6): hub-service entity 완성
  hub/build.gradle
  hub/src/main/java/com/yongyonglee/hub/domain/hub/exception/HubException.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/message/ExceptionMessage.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/model/Hub.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/model/converter/GeoLocationConverter.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/model/value_object/GeoLocation.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub_route/exception/HubRouteException.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub_route/message/ExceptionMessage.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub_route/model/HubRoute.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub_route/model/converter/TransitTimeToIntervalConverter.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub_route/model/value_object/TransitTime.java
  hub/src/main/java/com/yongyonglee/hub/domain/model/TimeBase.java
  hub/src/main/java/com/yongyonglee/hub/global/auditor/UserAuditorAware.java
  hub/src/main/java/com/yongyonglee/hub/global/config/JpaAuditingConfig.java
  hub/src/main/resources/application.yml
Labels: 🍀backend

#9 Feat/#5 order crud
  order/build.gradle
  order/src/main/java/com/yongyonglee/order/domain/delivery/controller/DeliveryController.java
  order/src/main/java/com/yongyonglee/order/domain/delivery/dto/DeliveryResponse.java
  order/src/main/java/com/yongyonglee/order/domain/delivery/entity/Delivery.java
  order/src/main/java/com/yongyonglee/order/domain/delivery/entity/DeliveryStatus.java
  order/src/main/java/com/yongyonglee/order/domain/delivery/repository/DeliveryRepository.java
  order/src/main/java/com/yongyonglee/order/domain/delivery/service/DeliveryService.java
  order/src/main/java/com/yongyonglee/order/domain/order/controller/OrderController.java
  order/src/main/java/com/yongyonglee/order/domain/order/dto/OrderCreateRequest.java
  order/src/main/java/com/yongyonglee/order/domain/order/dto/OrderResponse.java
  order/src/main/java/com/yongyonglee/order/domain/order/entity/Order.java
  order/src/main/java/com/yongyonglee/order/domain/order/repository/OrderRepository.java
  order/src/main/java/com/yongyonglee/order/domain/order/service/OrderService.java
  order/src/main/java/com/yongyonglee/order/global/entity/BaseTimeEntity.java
  order/src/main/java/com/yongyonglee/order/global/response/ApiResponse.java
  order/src/main/java/com/yongyonglee/order/global/response/CustomException.java
  order/src/main/java/com/yongyonglee/order/global/response/ErrorCode.java
  order/src/main/resources/application.yml
Labels: 🍀backend, 🌈feature

#12 Feat/#8 hub cr
  hub/build.gradle
  hub/src/main/java/com/yongyonglee/hub/domain/hub/controller/HubController.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/dto/request/CreateHubRequestDto.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/dto/response/CreateHubResponseDto.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/dto/response/HubResponseDto.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/message/ExceptionMessage.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/message/SuccessMessage.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/model/Hub.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/model/converter/GeoLocationConverter.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/model/value_object/GeoLocation.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/repository/HubRepository.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/service/HubService.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/service/HubServiceImpl.java
  hub/src/main/java/com/yongyonglee/hub/domain/model/TimeBase.java
  hub/src/main/java/com/yongyonglee/hub/global/aop/page/PageSizeAspect.java
  hub/src/main/java/com/yongyonglee/hub/global/aop/page/PageSizeLimit.java
  hub/src/main/java/com/yongyonglee/hub/global/config/WebSecurityConfig.java
  hub/src/main/java/com/yongyonglee/hub/global/exception/GlobalExceptionHandler.java
  hub/src/main/java/com/yongyonglee/hub/global/response/CommonResponse.java
  hub/src/main/java/com/yongyonglee/hub/global/response/ExceptionResponse.java
  hub/src/main/java/com/yongyonglee/hub/global/response/SuccessResponse.java
Labels: 🍀backend, 🌈feature

#14 Feat/#10 hub ud
  hub/src/main/java/com/yongyonglee/hub/domain/hub/controller/HubController.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/dto/request/UpdateHubRequestDto.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/dto/response/CreateHubResponseDto.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/dto/response/HubResponseDto.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/message/ExceptionMessage.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/message/SuccessMessage.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/model/Hub.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/repository/HubRepository.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/service/HubService.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/service/HubServiceImpl.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub_route/model/HubRoute.java
Labels: 🍀backend, ♻️refactor, 🌈feature

#15 Feat/#13 delivery route create
  order/src/main/java/com/yongyonglee/order/domain/delivery/entity/Delivery.java
  order/src/main/java/com/yongyonglee/order/domain/delivery/service/DeliveryService.java
  order/src/main/java/com/yongyonglee/order/domain/order/controller/OrderController.java
  order/src/main/java/com/yongyonglee/order/domain/route/HubRouteClient.java
  order/src/main/java/com/yongyonglee/order/domain/route/entity/Route.java
  order/src/main/java/com/yongyonglee/order/domain/route/repository/RouteRepository.java
  order/src/main/java/com/yongyonglee/order/domain/route/service/RouteService.java
Labels: 🍀backend, 🌈feature

#20 Feat/#17 order update delete
  order/src/main/java/com/yongyonglee/order/domain/delivery/entity/Delivery.java
  order/src/main/java/com/yongyonglee/order/domain/delivery/service/DeliveryService.java
  order/src/main/java/com/yongyonglee/order/domain/order/controller/OrderController.java
  order/src/main/java/com/yongyonglee/order/domain/order/dto/OrderUpdateDto.java
  order/src/main/java/com/yongyonglee/order/domain/order/entity/Order.java
  order/src/main/java/com/yongyonglee/order/domain/order/repository/OrderRepository.java
  order/src/main/java/com/yongyonglee/order/domain/order/service/OrderService.java
  order/src/main/java/com/yongyonglee/order/global/response/ErrorCode.java
Labels: 🍀backend, 🌈feature

#22 Feat/#11 hub swagger
  hub/build.gradle
  hub/src/main/java/com/yongyonglee/hub/domain/hub/controller/HubController.java
  hub/src/main/java/com/yongyonglee/hub/global/config/SwaggerConfig.java
Labels: 🍀backend, ⚙️setting, 📝docs

#21 Feat/#19 vendor create get
  vendor/build.gradle
  vendor/src/main/java/com/yongyonglee/vendor/domain/vendor/controller/VendorController.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/vendor/dto/request/CreateVendorRequestDto.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/vendor/dto/response/VendorResponseDto.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/vendor/exception/VendorException.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/vendor/message/ExceptionMessage.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/vendor/message/SuccessMessage.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/vendor/model/Vendor.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/vendor/model/constant/VendorCategory.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/vendor/repository/VendorRepository.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/vendor/service/VendorService.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/vendor/service/VendorServiceImpl.java
  vendor/src/main/java/com/yongyonglee/vendor/global/aop/page/PageSizeAspect.java
  vendor/src/main/java/com/yongyonglee/vendor/global/aop/page/PageSizeLimit.java
  vendor/src/main/java/com/yongyonglee/vendor/global/config/WebSecurityConfig.java
  vendor/src/main/java/com/yongyonglee/vendor/global/exception/GlobalExceptionHandler.java
  vendor/src/main/java/com/yongyonglee/vendor/global/response/CommonResponse.java
  vendor/src/main/java/com/yongyonglee/vendor/global/response/ExceptionResponse.java
  vendor/src/main/java/com/yongyonglee/vendor/global/response/SuccessResponse.java
Labels: 🍀backend, ⚙️setting, 🌈feature

#28 Feat/#23 vendor update delete
  vendor/src/main/java/com/yongyonglee/vendor/VendorApplication.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/client/HubClient.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/vendor/controller/VendorController.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/vendor/dto/request/UpdateVendorRequestDto.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/vendor/message/ExceptionMessage.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/vendor/model/Vendor.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/vendor/service/VendorService.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/vendor/service/VendorServiceImpl.java
Labels: 🍀backend, 🌈feature

#27 Feat/#24 hub-route CRUD
  hub/src/main/java/com/yongyonglee/hub/domain/hub/service/HubService.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/service/HubServiceImpl.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub_route/controller/HubRouteController.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub_route/dto/request/CreateHubRouteRequestDto.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub_route/dto/request/UpdateHubRouteRequestDto.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub_route/dto/response/HubRouteResponseDto.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub_route/exception/HubRouteException.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub_route/message/ExceptionMessage.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub_route/message/SuccessMessage.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub_route/model/HubRoute.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub_route/model/converter/TransitTimeToIntervalConverter.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub_route/model/value_object/TransitTime.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub_route/repository/HubRouteRepository.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub_route/service/HubRouteHelper.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub_route/service/HubRouteService.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub_route/service/HubRouteServiceImpl.java
  hub/src/main/resources/application.yml
Labels: 🍀backend, 🌈feature

#25 Feat/#13 delivery route create
  order/src/main/java/com/yongyonglee/order/OrderApplication.java
  order/src/main/java/com/yongyonglee/order/domain/delivery/entity/DeliveryStatus.java
  order/src/main/java/com/yongyonglee/order/domain/delivery/service/DeliveryService.java
  order/src/main/java/com/yongyonglee/order/domain/route/HubRouteClient.java
  order/src/main/java/com/yongyonglee/order/domain/route/HubRouteResponse.java
  order/src/main/java/com/yongyonglee/order/domain/route/VendorClient.java
  order/src/main/java/com/yongyonglee/order/domain/route/VendorResponseDto.java
  order/src/main/java/com/yongyonglee/order/domain/route/entity/Route.java
  order/src/main/java/com/yongyonglee/order/domain/route/service/RouteService.java
  order/src/main/java/com/yongyonglee/order/global/response/ErrorCode.java
Labels: 🍀backend, 🌈feature

#33 Feat/#29 product crud
  vendor/build.gradle
  vendor/src/main/java/com/yongyonglee/vendor/domain/product/controller/ProductController.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/product/dto/request/CreateProductRequestDto.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/product/dto/request/UpdateProductQuantityRequestDto.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/product/dto/response/ProductResponseDto.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/product/exception/ProductException.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/product/message/ExceptionMessage.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/product/message/SuccessMessage.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/product/model/Product.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/product/repository/ProductRepository.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/product/service/ProductService.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/product/service/ProductServiceImpl.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/vendor/service/VendorService.java
  vendor/src/main/java/com/yongyonglee/vendor/domain/vendor/service/VendorServiceImpl.java
  vendor/src/main/java/com/yongyonglee/vendor/global/config/SwaggerConfig.java
Labels: 🍀backend, 🌈feature

#39 Setting/#37 zipkin setting
  hub/build.gradle
  hub/src/main/resources/application.yml
  message/build.gradle
  message/src/main/resources/application.yml
  order/build.gradle
  order/src/main/resources/application.yml
  vendor/build.gradle
  vendor/src/main/resources/application.yml
Labels: ⚙️setting

#35 Refactor/#34 hub caching
  hub/src/main/java/com/yongyonglee/hub/HubApplication.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/dto/response/CreateHubResponseDto.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/dto/response/HubResponseDto.java
  hub/src/main/java/com/yongyonglee/hub/domain/hub/service/HubServiceImpl.java
  hub/src/main/java/com/yongyonglee/hub/global/config/CacheConfig.java
  hub/src/main/resources/application.yml
Labels: 🍀backend, ♻️refactor, 💾db

#46 fix: lastCommit for project
  hub/build.gradle
  order/build.gradle
  order/src/main/java/com/yongyonglee/order/domain/delivery/VendorResponseWrapper.java
  order/src/main/java/com/yongyonglee/order/domain/delivery/entity/Delivery.java
  order/src/main/java/com/yongyonglee/order/domain/delivery/service/DeliveryService.java
  order/src/main/java/com/yongyonglee/order/domain/order/controller/OrderController.java
  order/src/main/java/com/yongyonglee/order/domain/order/entity/Order.java
  order/src/main/java/com/yongyonglee/order/domain/route/HubRouteClient.java
  order/src/main/java/com/yongyonglee/order/domain/route/HubRouteResponseWrapper.java
  order/src/main/java/com/yongyonglee/order/domain/route/VendorClient.java
  order/src/main/java/com/yongyonglee/order/domain/route/dto/HubRouteResponseDto.java
  order/src/main/java/com/yongyonglee/order/domain/route/entity/Route.java
  order/src/main/java/com/yongyonglee/order/domain/route/service/RouteService.java
Labels: 🐞bug
